[project]
name = "mcp-interactive"
version = "0.1.0"
description = "MCP Interactive Service for Cursor and Windsurf"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "fastmcp>=2.3.0",
    "python-dotenv>=1.1.0",
    "typer>=0.15.0",
    "httpx>=0.24.0",
    "psutil>=5.9.0",
]

[project.optional-dependencies]
tkinter = []
pyqt = ["PyQt5>=5.15.0"]
web = ["flask>=2.0.0", "flask-socketio>=5.0.0"]
all = ["PyQt5>=5.15.0", "flask>=2.0.0", "flask-socketio>=5.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ai-interaction"]
